### ISSUE TITLE
[Request] ScrapBox Loot

### ISSUE THREAD

**Issue by Xaikii** [Trinsdar/IC2ClassicTweaker#1]
Could you possibly add a Method to change/remove Loot from Scratchboxes for CT?

**Comment by DbpGaming** [comment]
if ic2c uses the api for scrapboxs, you can use ic2tweaker for that (ic2ctweaker wasnt supposed to do anything ic2tweaker does as its supposed to be just an "addon" for ic2c content) heres the doc for the scrapbox stuff in ic2tweaker https://github.com/Team-AbCiv/IC2Tweaker/blob/bleeding/doc/ScrapBox.md

**Comment by Speiger** [comment]
@DbpGaming this can only add Scrapbox entries and not modify them or remove them (remove&add)
IC2 Exp has no api to remove Scrapbox entries while ic2c does.
Edit he wants to remove the netherstar out of the pool.

**Comment by DbpGaming** [comment]
ah, that makes sense can't you worst case disable that via config though? or does ic2c not generate scrapbox recipe configs

**Comment by DbpGaming** [comment]
speiger dm'd me about this yeah, that worst case isn't even possible so proper support via ic2c tweaker would be needed for removals

**Comment by Trinsdar** [comment]
Yah I can add a method

**Comment by Trinsdar** [comment]
added in latest update
